.build:
  image: docker:27.4.0-rc.2-cli
  services:
    - docker:27.4.0-rc.2-dind
  script:
    - apk add --no-chache jq httpie
    - export $JSON_VERSION=$(cat $MS_DIR/package.json | jq -r .version )
      #saving version in pakage.json file

    - export VERSIONED_IMAGE=$MICROSERVICE:$JSON_VERSION.$CI_PIPELINE_ID
      #creating a versioned image for each microservice

    - echo "VERSIONED_IMAGE=$VERSIONED_IMAGE" >> environmental-variables.env
      #saving the versioned image into an environmental file

    - docker build -t $CI_REGISTRY_IMAGE/$VERSIONED_IMAGE $MS_DIR
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$VERSIONED_IMAGE
    - echo $VERSIONED_IMAGE
  variables:
    MICROSERVICE: ""
    MS_VERSION: ""
    MS_DIR: ""
  artifacts:
    reports:
      dotenv: environmental-variables.env

build_frontend:
  extends: .build
  variables:
    MICROSERVICE: frontend
    MS_VERSION: 2.0
    MS_DIR: frontend-Dir

build_products:
  extends: .build
  variables:
    MICROSERVICE: products
    MS_VERSION: 2.0
    MS_DIR: products-Dir
  needs:
    - build_frontend

build_shoppingcart:
  extends: .build
  variables:
    MICROSERVICE: shoppingcart
    MS_VERSION: 2.0
    MS_DIR: shoppingcart-Dir
  needs:
    - build_frontend
