build_frontend:
  image: docker:27.4.0-rc.2-cli
  services:
    - docker:27.4.0-rc.2-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:1.0 frontend-Dir
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/frontend:1.0

build_products:
  image: docker:27.4.0-rc.2-cli
  services:
    - docker:27.4.0-rc.2-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/products:1.0 products-Dir
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/products:1.0

build_shoppingcart:
  image: docker:27.4.0-rc.2-cli
  services:
    - docker:27.4.0-rc.2-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/shoppingcart:1.0 shoppingcart-Dir
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/shoppingcart:1.0
