.build:
  image: docker:27.4.0-rc.2-cli
  services:
    - docker:27.4.0-rc.2-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$MICROSERVICE:$MS_VERSION $MS_DIR
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$MICROSERVICE:$MS_VERSION
  variables:
    MICROSERVICE: ""
    MS_VERSION: ""
    MS_DIR: ""

build_frontend:
  extends: .build
  variables:
    MICROSERVICE: frontend
    MS_VERSION: 2.0
    MS_DIR: frontend-Dir

build_products:
  extends: .build
  variables:
    MICROSERVICE: products
    MS_VERSION: 2.0
    MS_DIR: products-Dir
  needs:
    - build_frontend

build_shoppingcart:
  extends: .build
  variables:
    MICROSERVICE: shoppingcart
    MS_VERSION: 2.0
    MS_DIR: shoppingcart-Dir
  needs:
    - build_frontend
