version: "3.6"
services:
  app:
    image: ${DC_IMAGE}
    ports:
      - ${DC_PORT}:${DC_CONTAINER_PORT}
    # Assign to a network or multiple networks
    networks:
      - microservice_network

networks:
  microservice_network:
    external:
      name: microservice_network

